import type {
  PlayingCardMeta,
  CharacterCardMeta,
  RoleCardMeta,
} from "../types";
import {
  bangBase,
  barrelBase,
  beerBase,
  carabineBase,
  cat_balouBase,
  duelBase,
  dynamiteBase,
  gatlingBase,
  general_storeBase,
  indiansBase,
  jailBase,
  missedBase,
  mustangBase,
  panicBase,
  remingtonBase,
  saloonBase,
  schofieldBase,
  scopeBase,
  stagecoachBase,
  volcanicBase,
  wells_cargoBase,
  winchesterBase,
} from "./cards.base.bases";

const REGULAR = {
  bang_01: {
    ...bangBase,
    rankAndSuit: { rank: "7", suit: "clubs" },
    cardInstanceId: "bang_01",
  },
  bang_02: {
    ...bangBase,
    image: "bang_2",
    rankAndSuit: { rank: "9", suit: "diamonds" },
    cardInstanceId: "bang_02",
  },
  bang_03: {
    ...bangBase,
    image: "bang_2",
    rankAndSuit: { rank: "5", suit: "clubs" },
    cardInstanceId: "bang_03",
  },
  bang_04: {
    ...bangBase,
    rankAndSuit: { rank: "Q", suit: "hearts" },
    cardInstanceId: "bang_04",
  },
  bang_05: {
    ...bangBase,
    image: "bang_2",
    rankAndSuit: { rank: "Q", suit: "diamonds" },
    cardInstanceId: "bang_05",
  },
  bang_06: {
    ...bangBase,
    image: "bang_2",
    rankAndSuit: { rank: "6", suit: "diamonds" },
    cardInstanceId: "bang_06",
  },
  bang_07: {
    ...bangBase,
    rankAndSuit: { rank: "7", suit: "diamonds" },
    cardInstanceId: "bang_07",
  },
  bang_08: {
    ...bangBase,
    image: "bang_2",
    rankAndSuit: { rank: "9", suit: "clubs" },
    cardInstanceId: "bang_08",
  },
  bang_09: {
    ...bangBase,
    image: "bang_2",
    rankAndSuit: { rank: "8", suit: "diamonds" },
    cardInstanceId: "bang_09",
  },
  bang_10: {
    ...bangBase,
    rankAndSuit: { rank: "8", suit: "clubs" },
    cardInstanceId: "bang_10",
  },
  bang_11: {
    ...bangBase,
    image: "bang_2",
    rankAndSuit: { rank: "10", suit: "diamonds" },
    cardInstanceId: "bang_11",
  },
  bang_12: {
    ...bangBase,
    image: "bang_2",
    rankAndSuit: { rank: "5", suit: "diamonds" },
    cardInstanceId: "bang_12",
  },
  bang_13: {
    ...bangBase,
    rankAndSuit: { rank: "K", suit: "hearts" },
    cardInstanceId: "bang_13",
  },
  bang_14: {
    ...bangBase,
    image: "bang_2",
    rankAndSuit: { rank: "K", suit: "diamonds" },
    cardInstanceId: "bang_14",
  },
  bang_15: {
    ...bangBase,
    image: "bang_2",
    rankAndSuit: { rank: "6", suit: "clubs" },
    cardInstanceId: "bang_15",
  },
  bang_16: {
    ...bangBase,
    rankAndSuit: { rank: "3", suit: "diamonds" },
    cardInstanceId: "bang_16",
  },
  bang_17: {
    ...bangBase,
    image: "bang_2",
    rankAndSuit: { rank: "3", suit: "clubs" },
    cardInstanceId: "bang_17",
  },
  bang_18: {
    ...bangBase,
    image: "bang_2",
    rankAndSuit: { rank: "J", suit: "diamonds" },
    cardInstanceId: "bang_18",
  },
  bang_19: {
    ...bangBase,
    rankAndSuit: { rank: "2", suit: "clubs" },
    cardInstanceId: "bang_19",
  },
  bang_20: {
    ...bangBase,
    image: "bang_2",
    rankAndSuit: { rank: "A", suit: "diamonds" },
    cardInstanceId: "bang_20",
  },
  bang_21: {
    ...bangBase,
    image: "bang_2",
    rankAndSuit: { rank: "2", suit: "diamonds" },
    cardInstanceId: "bang_21",
  },
  bang_22: {
    ...bangBase,
    rankAndSuit: { rank: "A", suit: "hearts" },
    cardInstanceId: "bang_22",
  },
  bang_23: {
    ...bangBase,
    image: "bang_2",
    rankAndSuit: { rank: "A", suit: "spades" },
    cardInstanceId: "bang_23",
  },
  bang_24: {
    ...bangBase,
    rankAndSuit: { rank: "4", suit: "clubs" },
    cardInstanceId: "bang_24",
  },
  bang_25: {
    ...bangBase,
    rankAndSuit: { rank: "4", suit: "diamonds" },
    cardInstanceId: "bang_25",
  },
  barrel_01: {
    ...barrelBase,
    rankAndSuit: { rank: "Q", suit: "spades" },
    cardInstanceId: "barrel_01",
  },
  barrel_02: {
    ...barrelBase,
    rankAndSuit: { rank: "K", suit: "spades" },
    cardInstanceId: "barrel_02",
  },
  beer_01: {
    ...beerBase,
    rankAndSuit: { rank: "J", suit: "hearts" },
    cardInstanceId: "beer_01",
  },
  beer_02: {
    ...beerBase,
    rankAndSuit: { rank: "10", suit: "hearts" },
    cardInstanceId: "beer_02",
  },
  beer_03: {
    ...beerBase,
    rankAndSuit: { rank: "8", suit: "hearts" },
    cardInstanceId: "beer_03",
  },
  beer_04: {
    ...beerBase,
    rankAndSuit: { rank: "9", suit: "hearts" },
    cardInstanceId: "beer_04",
  },
  beer_05: {
    ...beerBase,
    rankAndSuit: { rank: "6", suit: "hearts" },
    cardInstanceId: "beer_05",
  },
  beer_06: {
    ...beerBase,
    rankAndSuit: { rank: "7", suit: "hearts" },
    cardInstanceId: "beer_06",
  },
  cat_balou_01: {
    ...cat_balouBase,
    rankAndSuit: { rank: "K", suit: "hearts" },
    cardInstanceId: "cat_balou_01",
  },
  cat_baloue_02: {
    ...cat_balouBase,
    rankAndSuit: { rank: "J", suit: "diamonds" },
    cardInstanceId: "cat_balou_02",
  },
  cat_balou_03: {
    ...cat_balouBase,
    rankAndSuit: { rank: "9", suit: "diamonds" },
    cardInstanceId: "cat_balou_03",
  },
  cat_baloue_04: {
    ...cat_balouBase,
    rankAndSuit: { rank: "10", suit: "diamonds" },
    cardInstanceId: "cat_balou_04",
  },
  duel_01: {
    ...duelBase,
    rankAndSuit: { rank: "8", suit: "clubs" },
    cardInstanceId: "duel_01",
  },
  duel_02: {
    ...duelBase,
    rankAndSuit: { rank: "J", suit: "spades" },
    cardInstanceId: "duel_02",
  },
  duel_03: {
    ...duelBase,
    rankAndSuit: { rank: "Q", suit: "diamonds" },
    cardInstanceId: "duel_03",
  },
  dynamite_01: {
    ...dynamiteBase,
    rankAndSuit: { rank: "2", suit: "hearts" },
    cardInstanceId: "dynamite_01",
  },
  gatling_01: {
    ...gatlingBase,
    rankAndSuit: { rank: "10", suit: "hearts" },
    cardInstanceId: "gatling_01",
  },
  general_store_01: {
    ...general_storeBase,
    rankAndSuit: { rank: "Q", suit: "spades" },
    cardInstanceId: "general_store_01",
  },
  general_store_02: {
    ...general_storeBase,
    rankAndSuit: { rank: "9", suit: "clubs" },
    cardInstanceId: "general_store_02",
  },
  indians_01: {
    ...indiansBase,
    rankAndSuit: { rank: "A", suit: "diamonds" },
    cardInstanceId: "indians_01",
  },
  indians_02: {
    ...indiansBase,
    rankAndSuit: { rank: "K", suit: "diamonds" },
    cardInstanceId: "indians_02",
  },
  jail_01: {
    ...jailBase,
    rankAndSuit: { rank: "10", suit: "spades" },
    cardInstanceId: "jail_01",
  },
  jail_02: {
    ...jailBase,
    rankAndSuit: { rank: "J", suit: "spades" },
    cardInstanceId: "jail_02",
  },
  jail_03: {
    ...jailBase,
    rankAndSuit: { rank: "4", suit: "hearts" },
    cardInstanceId: "jail_03",
  },
  missed_01: {
    ...missedBase,
    rankAndSuit: { rank: "3", suit: "clubs" },
    cardInstanceId: "missed_01",
  },
  missed_02: {
    ...missedBase,
    rankAndSuit: { rank: "A", suit: "clubs" },
    cardInstanceId: "missed_02",
  },
  missed_03: {
    ...missedBase,
    rankAndSuit: { rank: "10", suit: "clubs" },
    cardInstanceId: "missed_03",
  },
  missed_04: {
    ...missedBase,
    rankAndSuit: { rank: "2", suit: "spades" },
    cardInstanceId: "missed_04",
  },
  missed_05: {
    ...missedBase,
    rankAndSuit: { rank: "4", suit: "spades" },
    cardInstanceId: "missed_05",
  },
  missed_06: {
    ...missedBase,
    rankAndSuit: { rank: "8", suit: "spades" },
    cardInstanceId: "missed_06",
  },
  missed_07: {
    ...missedBase,
    rankAndSuit: { rank: "3", suit: "spades" },
    cardInstanceId: "missed_07",
  },
  missed_08: {
    ...missedBase,
    rankAndSuit: { rank: "5", suit: "spades" },
    cardInstanceId: "missed_08",
  },
  missed_09: {
    ...missedBase,
    rankAndSuit: { rank: "7", suit: "spades" },
    cardInstanceId: "missed_09",
  },
  missed_10: {
    ...missedBase,
    rankAndSuit: { rank: "6", suit: "spades" },
    cardInstanceId: "missed_10",
  },
  missed_11: {
    ...missedBase,
    rankAndSuit: { rank: "Q", suit: "clubs" },
    cardInstanceId: "missed_11",
  },
  missed_12: {
    ...missedBase,
    rankAndSuit: { rank: "K", suit: "clubs" },
    cardInstanceId: "missed_12",
  },
  mustang_01: {
    ...mustangBase,
    rankAndSuit: { rank: "9", suit: "hearts" },
    cardInstanceId: "mustang_01",
  },
  mustang_02: {
    ...mustangBase,
    rankAndSuit: { rank: "8", suit: "hearts" },
    cardInstanceId: "mustang_02",
  },
  panic_01: {
    ...panicBase,
    rankAndSuit: { rank: "A", suit: "hearts" },
    cardInstanceId: "panic_01",
  },
  panic_02: {
    ...panicBase,
    rankAndSuit: { rank: "Q", suit: "hearts" },
    cardInstanceId: "panic_02",
  },
  panic_03: {
    ...panicBase,
    rankAndSuit: { rank: "8", suit: "diamonds" },
    cardInstanceId: "panic_03",
  },
  panic_04: {
    ...panicBase,
    rankAndSuit: { rank: "J", suit: "hearts" },
    cardInstanceId: "panic_04",
  },
  scope_01: {
    ...scopeBase,
    rankAndSuit: { rank: "A", suit: "spades" },
    cardInstanceId: "scope_01",
  },
  saloon_01: {
    ...saloonBase,
    rankAndSuit: { rank: "5", suit: "hearts" },
    cardInstanceId: "saloon_01",
  },
  stagecoach_01: {
    ...stagecoachBase,
    rankAndSuit: { rank: "9", suit: "spades" },
    cardInstanceId: "stagecoach_01",
  },
  stagecoach_02: {
    ...stagecoachBase,
    rankAndSuit: { rank: "9", suit: "spades" },
    cardInstanceId: "stagecoach_02",
  },
  wells_fargo_01: {
    ...wells_cargoBase,
    rankAndSuit: { rank: "3", suit: "hearts" },
    cardInstanceId: "wells_fargo_01",
  },
} satisfies Record<string, PlayingCardMeta>;

const WEAPONS = {
  carabine_01: {
    ...carabineBase,
    rankAndSuit: { rank: "A", suit: "clubs" },
    cardInstanceId: "carabine_01",
  },
  winchester_01: {
    ...winchesterBase,
    rankAndSuit: { rank: "8", suit: "spades" },
    cardInstanceId: "winchester_01",
  },
  remington_01: {
    ...remingtonBase,
    rankAndSuit: { rank: "K", suit: "clubs" },
    cardInstanceId: "remington_01",
  },
  schofiled_01: {
    ...schofieldBase,
    rankAndSuit: { rank: "J", suit: "clubs" },
    cardInstanceId: "schofiled_01",
  },
  schofiled_02: {
    ...schofieldBase,
    rankAndSuit: { rank: "K", suit: "spades" },
    cardInstanceId: "schofiled_02",
  },
  schofiled_03: {
    ...schofieldBase,
    rankAndSuit: { rank: "Q", suit: "clubs" },
    cardInstanceId: "schofiled_03",
  },
  volcanic_01: {
    ...volcanicBase,
    rankAndSuit: { rank: "10", suit: "clubs" },
    cardInstanceId: "volcanic_01",
  },
  volcanic_02: {
    ...volcanicBase,
    rankAndSuit: { rank: "10", suit: "spades" },
    cardInstanceId: "volcanic_02",
  },
} satisfies Record<string, PlayingCardMeta>;

const CHARACTERS = {
  bart_cassidy: {
    cardTypeId: "bart_cassidy",
    bullets: 4,
    image: "bart_cassidy",
    borderColor: "green",
    borderType: "base",
    decorations: ["bullet_holes"],
    description: [[{ type: "text", key: "bart_cassidy" }]],
    pack: "base",
  },
  black_jack: {
    cardTypeId: "black_jack",
    bullets: 4,
    image: "black_jack",
    borderColor: "green",
    borderType: "base",
    decorations: ["bullet_holes"],
    description: [[{ type: "text", key: "black_jack" }]],
    pack: "base",
  },
  calamity_janet: {
    cardTypeId: "calamity_janet",
    bullets: 4,
    image: "calamity_janet",
    borderColor: "green",
    borderType: "base",
    decorations: ["bullet_holes"],
    description: [[{ type: "text", key: "calamity_janet" }]],
    pack: "base",
  },
  el_gringo: {
    cardTypeId: "el_gringo",
    bullets: 3,
    image: "el_gringo",
    borderColor: "green",
    borderType: "base",
    decorations: ["bullet_holes"],
    description: [[{ type: "text", key: "el_gringo" }]],
    pack: "base",
  },
  jesse_jones: {
    cardTypeId: "jesse_jones",
    bullets: 4,
    image: "jesse_jones",
    borderColor: "green",
    borderType: "base",
    decorations: ["bullet_holes"],
    description: [[{ type: "text", key: "jesse_jones" }]],
    pack: "base",
  },
  jourdonnais: {
    cardTypeId: "jourdonnais",
    bullets: 4,
    image: "jourdonnais",
    borderColor: "green",
    borderType: "base",
    decorations: ["bullet_holes"],
    description: [[{ type: "text", key: "jourdonnais" }]],
    pack: "base",
  },
  kit_carlson: {
    cardTypeId: "kit_carlson",
    bullets: 4,
    image: "kit_carlson",
    borderColor: "green",
    borderType: "base",
    decorations: ["bullet_holes"],
    description: [[{ type: "text", key: "kit_carlson" }]],
    pack: "base",
  },
  lucky_duke: {
    cardTypeId: "lucky_duke",
    bullets: 4,
    image: "lucky_duke",
    borderColor: "green",
    borderType: "base",
    decorations: ["bullet_holes"],
    description: [[{ type: "text", key: "lucky_duke" }]],
    pack: "base",
  },
  paul_regret: {
    cardTypeId: "paul_regret",
    bullets: 3,
    image: "paul_regret",
    borderColor: "green",
    borderType: "base",
    decorations: ["bullet_holes"],
    description: [[{ type: "text", key: "paul_regret" }]],
    pack: "base",
  },
  pedro_ramirez: {
    cardTypeId: "pedro_ramirez",
    bullets: 4,
    image: "pedro_ramirez",
    borderColor: "green",
    borderType: "base",
    decorations: ["bullet_holes"],
    description: [[{ type: "text", key: "pedro_ramirez" }]],
    pack: "base",
  },
  rose_doolan: {
    cardTypeId: "rose_doolan",
    bullets: 4,
    image: "rose_doolan",
    borderColor: "green",
    borderType: "base",
    decorations: ["bullet_holes"],
    description: [[{ type: "text", key: "rose_doolan" }]],
    pack: "base",
  },
  sid_ketchum: {
    cardTypeId: "sid_ketchum",
    bullets: 4,
    image: "sid_ketchum",
    borderColor: "green",
    borderType: "base",
    decorations: ["bullet_holes"],
    description: [[{ type: "text", key: "sid_ketchum" }]],
    pack: "base",
  },
  slab_the_killer: {
    cardTypeId: "slab_the_killer",
    bullets: 4,
    image: "slab_the_killer",
    borderColor: "green",
    borderType: "base",
    decorations: ["bullet_holes"],
    description: [[{ type: "text", key: "slab_the_killer" }]],
    pack: "base",
  },
  suzy_lafayette: {
    cardTypeId: "suzy_lafayette",
    bullets: 4,
    image: "suzy_lafayette",
    borderColor: "green",
    borderType: "base",
    decorations: ["bullet_holes"],
    description: [[{ type: "text", key: "suzy_lafayette" }]],
    pack: "base",
  },
  vulture_sam: {
    cardTypeId: "vulture_sam",
    bullets: 4,
    image: "vulture_sam",
    borderColor: "green",
    borderType: "base",
    decorations: ["bullet_holes"],
    description: [[{ type: "text", key: "vulture_sam" }]],
    pack: "base",
  },
  willy_the_kid: {
    cardTypeId: "willy_the_kid",
    bullets: 4,
    image: "willy_the_kid",
    borderColor: "green",
    borderType: "base",
    decorations: ["bullet_holes"],
    description: [[{ type: "text", key: "willy_the_kid" }]],
    pack: "base",
  },
} satisfies Record<string, CharacterCardMeta>;

const ROLES = {
  sheriff: {
    cardTypeId: "sheriff",
    image: "sheriff",
    decorations: ["bullet_holes"],
    borderType: "none",
    borderColor: "none",
    description: [[{ type: "text", key: "sheriff" }]],
    pack: "base",
  },
  outlaw: {
    cardTypeId: "outlaw",
    image: "outlaw",
    decorations: ["bullet_holes"],
    borderType: "none",
    borderColor: "none",
    description: [[{ type: "text", key: "outlaw" }]],
    pack: "base",
  },
  deputy: {
    cardTypeId: "deputy",
    image: "deputy",
    decorations: ["bullet_holes"],
    borderType: "none",
    borderColor: "none",
    description: [[{ type: "text", key: "deputy" }]],
    pack: "base",
  },
  renegade: {
    cardTypeId: "renegade",
    image: "renegade",
    decorations: ["bullet_holes"],
    borderType: "none",
    borderColor: "none",
    description: [[{ type: "text", key: "renegade" }]],
    pack: "base",
  },
} satisfies Record<string, RoleCardMeta>;

export const CARDS_BASE = {
  REGULAR,
  WEAPONS,
  CHARACTERS,
  ROLES,
};
